### ISSUE TITLE
Error: The dataProvider threw an error. It should return a rejected Promise instead.

### ISSUE THREAD

**Issue by braco** [BowlingX/ra-postgraphile#21] opened 2020-06-14 20:34 UTC
Getting this full page, fatal error when issues like #20 arise:

`Error: The dataProvider threw an error. It should return a rejected Promise instead.`

Is this by design? I'm setting up like so:
```
    useEffect(() => {
        if (client) {
            (async () => {
                const dataProvider = await pgDataProvider(client);
                setDataProvider(() => dataProvider);
            })()    
        }
    }, [client]);
```

**Comment by christiaanwesterbeek** [comment] 2020-06-15 07:01
I just checked the source code of react-admin. I think the error message (and cause) is logged in your console. See the console.error line.

https://github.com/marmelab/react-admin/blob/aeda86582e6ac1ea37f29739a8f08743694616c9/packages/ra-core/src/dataProvider/useDataProvider.ts#L470-L475

**Comment by affluent-bilby-classifieds** [comment] 2020-07-02 07:52
Hi braco,
I had a similar problem but I don't know if the root cause different to your issue.
Did you get something in the console like the following?:
` index.js:1 Warning: Failed prop type: The prop `children` is marked as required in `ForwardRef(Link)`, but its value is `null``

I posted my issue to [Stackoverflow](https://stackoverflow.com/questions/62657963/react-admin-the-dataprovider-threw-an-error-it-should-return-a-rejected-promis)

**Comment by affluent-bilby-classifieds** [comment] 2020-07-05 12:06
Also have you guys seen this?
I would be keen to see how it compares to this project.

https://gist.github.com/hendrikniemann/83648da05161a36e84c0ee4ab61ad605

**Comment by BowlingX** [comment] 2020-07-10 15:44
Hi :). In your case, it seems like the id is missing for your relation. We definitely can improve error messages and handling.

**Comment by BowlingX** [comment] 2020-07-13 11:33
Related to #29

**Comment by BowlingX** [comment] 2020-07-21 11:54
I will close this issue for now. The related bug has been fixed.

**Closed by BowlingX** 2020-07-21 11:54 UTC
Labels: enhancement
